# Generated by Django 3.1.4 on 2020-12-23 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=280)),
                ('user', models.CharField(max_length=50)),
                ('tweet_id', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('sentiment', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
