# Generated by Django 3.1.4 on 2020-12-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetSentiment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teets',
            new_name='Tweet',
        ),
    ]
