# Generated by Django 3.1.4 on 2020-12-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetSentiment', '0005_auto_20201223_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='score',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='sentiment',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
